server:
  port: 30004

spring:
  data:
    elasticsearch:
      #节点名字，默认elasticsearch
      cluster-name: elasticsearch
      #节点地址，多个节点用逗号隔开
      cluster-nodes: 127.0.0.1:9300
      #spring.data.elasticsearch.local=false
      repositories:
        enable: true
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf6t5d12zma8fb1m00o.mysql.rds.aliyuncs.com:3306/heli_mall?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: heli
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化大小
      initial-size: 5
      #最小值
      min-idle: 5
      #最大值
      max-active: 20
      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #'wall'用于防火墙，SpringBoot中没有log4j，我改成了log4j2
      filters: stat,wall,log4j2
      #最大PSCache连接
      max-pool-prepared-statement-perconnection-size: 20
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties:
        druid.stat.mergeSql: true
        druid.stat.slowSqlMillis: 500
      # 配置StatFilter
      web-stat-filter:
        #默认为false，设置为true启动
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: false
        session-stat-max-count: 1000
        principal-session-name: admin
        principal-cookie-name: admin
        profile-enable: true
      #配置StatViewServlet
      stat-view-servlet:
        #启用
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
        #是否可以重置
        reset-enable: true
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    timeout: 10000

welcome: micro-order-dev

logging:
  config: classpath:dev-log.xml

token_exp_time: 2592000
captcha_exp_time: 10
captcha_length: 4
captcha_max_num: 50

mybatis:
  mapper-locations: classpath:mapper/auto/*.xml,classpath:mapper/manual/*.xml
  type-aliases-package: com.ydhl.micro.*.entity

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: false
  params: count=countSql
  returnPageInfo: check

wx:
  code2sessionUrl: https://api.weixin.qq.com/sns/jscode2session?appid={?}&secret={?}&js_code={?}&grant_type=authorization_code
  liteapp:
    appId: wx9bca6efcf235104d
    appSecret: 2bdb4db73744e62eca5e69ce04074561

#合力云平台api
heli:
  api:
    deviceId: HMP_01501
    appId: HMP_015
    loginUrl: http://220.178.74.185:17777/api/Login
    smsUrl: http://220.178.74.185:17777/api/SendToMsgs?token={?}

#静态资源访问路径
upload:
  # 运营平台静态资源上传路径
  dir: D:\\heli\\files
  # 运营平台静态资源访问路径
  url: http://minisht.localhost.com/files/
