server:
  port: 20001

spring:
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    timeout: 10000

welcome: client-admin-prod

logging:
  config: classpath:prod-log.xml

#静态资源访问路径
upload:
  # 运营平台静态资源上传路径
  dir: /u01/app/web/files/
  # 运营平台静态资源访问路径
  url: http://minisht.helichina.com/files/
